# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Playground' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # SSZipArchive - Utility class for zipping and unzipping files
  # https://github.com/ZipArchive/ZipArchive
  pod 'SSZipArchive'
  
  pod 'AGenUI', :podspec => 'https://amap-style-anole.cn-hangzhou.oss-cdn.aliyun-inc.com/agenui/ios/AGenUI_0_9_8_2.podspec'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
  
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
